# Generated by Django 3.1.5 on 2021-01-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remaining_points',
            field=models.IntegerField(default=0),
        ),
    ]
